image: node:latest

services:
  - mongo:latest

cache:
  paths:
    - node_modules/

variables:
  MONGODB_TESTING_URI: 'mongodb://mongo/testing'

test:
  script:
    - npm install
    - npm run test
  
coverage:
  script:
    - npm install
    - npm run coverage