image: node:latest

services:
  - mongo:latest
  - postgres:latest

variables:
  PASSWORD: 'postgres'
  POSTGRES_PASSWORD: 'postgres'

test:
  script:
    - npm install
    - npm run test

coverage:
  script:
    - npm install
    - npm run test
    - npm run coverage
  allow_failure: true