image: node:latest

services:
  - mongo:latest
  - postgres:latest

variables:
  DB_USERNAME: runner
  PASSWORD: ''

test:
  script:
    - npm install
    - npm run test

coverage:
  script:
    - npm install
    - npm run test
    - npm run coverage
  allow_failure: true