image: node:latest

services:
  - mongo:latest
  - postgres:latest

variables:
  DB_HOST: 'postgres'
  DATABASE: 'postgres'
  PASSWORD: 'postgres'
  POSTGRES_PASSWORD: 'postgres'

test:
  script:
    - npm install --ignore-scripts
    - npm run test

coverage:
  script:
    - npm install --ignore-scripts
    - npm run test
    - npm run coverage
  allow_failure: true