image: node:latest

services:
  - postgres:latest

variables:
  DB_HOST: 'postgres'
  DATABASE: 'postgres'
  PASSWORD: 'postgres'
  POSTGRES_PASSWORD: 'postgres'

test:
  script:
    - npm install
    - npm run test

coverage:
  script:
    - npm install
    - npm run test
    - npm run coverage
  allow_failure: true