  version: 2
  jobs:
    build:
      docker: 
        - image: circleci/node:12.0.0 # the primary container, where your job's commands are run
        - image: circleci/mongo:latest
      environment:
        MONGODB_TESTING_URI: 'mongodb://mongo/testing'
      steps:
        - checkout # check out the code in the project directory
        - run: npm install
        - run: npm run test
