  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/node:13.0.0 # the primary container, where your job's commands are run
        - image: circleci/mongo:latest
        - image: circleci/postgres:latest
          environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
      environment:
        MONGODB_TESTING_URI: 'mongodb://0.0.0.0:27017/testing'
        DB_HOST: 'localhost'
        DATABASE: 'postgres'
        PASSWORD: 'postgres'
        
      steps:
        - checkout # check out the code in the project directory
        - run: npm install --ignore-scripts
        - run: npm run test
