const express = require('express')
const router = express.Router()
const AuthRoute = require('./AuthRoute')
const TicketRoute = require('./ticket/TicketRoute')
const CategoryRoute = require('./ticket/CategoryRoute')
const GroupRoute = require('./ticket/GroupRoute')
const StatusRoute = require('./ticket/StatusRoute')
const SearchRoute = require('./ticket/SearchRoute')
const AddressRoute = require('./AddressRoute')
const AnalystRoute = require('./AnalystRoute')
const RoleRoute = require('./RoleRoute')
const ProfileRoute = require('./ProfileRoute')
const ChatRoute = require('./ChatRoute')
const NotificationRoute = require('./NotificationRoute')
const KnowledgeRoute = require('./knowledge/KnowledgeRoute')
const KnowledgeStatusRoute = require('./knowledge/KnowledgeStatusRoute')

router.use(AuthRoute)
router.use(TicketRoute)
router.use(CategoryRoute)
router.use(GroupRoute)
router.use(StatusRoute)
router.use(SearchRoute)
router.use(AddressRoute)
router.use(AnalystRoute)
router.use(RoleRoute)
router.use(ProfileRoute)
router.use(ChatRoute)
router.use(NotificationRoute)
router.use(KnowledgeRoute)
router.use(KnowledgeStatusRoute)

module.exports = router
