enum NotificationEnum {
  ADD_NOTIFICATION = 'ADD_NOTIFICATION',
  UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION',
  READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATIONS',
}

export default NotificationEnum;
