enum TicketEnum {
  TICKET_CREATE = 'TICKET_CREATE',
  TICKET_TRANSFER_TO_GROUP = 'TICKET_TRANSFER_TO_GROUP',
  TICKETS_TRANSFER_TO_GROUP = 'TICKETS_TRANSFER_TO_GROUP',
  TICKET_CHANGE_STATUS = 'TICKET_CHANGE_STATUS',
  TICKETS_CHANGE_STATUS = 'TICKETS_CHANGE_STATUS',
  TICKET_EDIT = 'TICKET_EDIT',
  ADD_CHILDREN = 'ADD_CHILDREN',
  REMOVE_CHILDREN = 'REMOVE_CHILDREN',
  SLA_UPDATE = 'SLA_UPDATE',
}

export default TicketEnum;
